spring.datasource.url=jdbc:postgresql://localhost:5432/sbdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# test user. gotta specify if not, we can't test it
spring.security.user.name=admin
spring.security.user.password=admin