"""
Django settings for robot_back project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
# Lines below added by reborn to allow connection with neon database
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o)o#=w_o9k^0jixz@5y3#2klyox(ckx4y^qs6070@r*ofeq8oy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Filled value from empty array to line below by reborn to allow koyeb to connect
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "LOCALHOST,127.0.0.1,[::1]").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Added by reborn below to connect with react
    'rest_framework',
    'corsheaders',
    # Apps created by reborn
]

INSTALLED_APPS += [
    'apps.robot_back_api',
    'apps.robot_auth',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Added by reborn below to connect with react
    'corsheaders.middleware.CorsMiddleware',
    # Added by reborn below to allow koyeb to deploy
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

# Added by reborn below to connect with react
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'robot_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'robot_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Edited below by reborn to allow database connection on neon.tech

from jproperties import Properties # type: ignore
import dj_database_url # type: ignore
configs = Properties() 
with open('./robot_back/conf.properties', 'rb') as read_prop: 
    configs.load(read_prop) 
prop_view = configs.items()
for item in prop_view: 
    databaseURL = item[1][0]

#Specification below comes from koyeb connection string
DATABASES = {
    "default": dj_database_url.parse(
        url=databaseURL,
        conn_max_age=600, conn_health_checks=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
#Two lines bellow added by reborn to allow koyeb to connect
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
